services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - ./conf/default.conf:/etc/nginx/conf.d/default.conf
        - ./html:/var/www/html

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"