services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/log:/var/log/nginx:rw
      - ./html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: host
    volumes:
      - ./fail2ban/jail.d:/etc/fail2ban/jail.d:ro
      - ./fail2ban/filter.d:/etc/fail2ban/filter.d:ro
      - fail2ban:/data
      - ./nginx/log:/var/log/nginx:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./nginx/log:/var/log/nginx:ro
      - ./html:/var/www/html:rw
    environment:
      - "HOOK=nginx -s reload"
    command: certonly --webroot -w /var/www/html --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAINS} --non-interactive --keep-until-expiring
    restart: unless-stopped

volumes:
  fail2ban:
